#!/bin/bash

KEY=1zJ9DDJ1pg79DhNKvcMUpN2p8zvvQY2S
URL=https://api.dynu.com/v2/dns
ID=8490924
RECORD_ID=3517649
bash getRecordData > test
sed -i -e "s/$(bash checkDNSPort)/$(bash ngrokgetip | cut -d ":" -f 2)/g" test
DATA="$(cat test)"

echo "$DATA" | python -m json.tool
curl -s -X POST $URL/$ID/record/$RECORD_ID \
	-H "accept: application/json" \
	-H "API-Key: $KEY" \
	-H "Content-Type: application/json" \
	-d "$DATA" | python -m json.tool
